name: phpcs

on: [push]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup composer cache
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: php-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-composer-

      - name: Set php version to 7.4
        run: update-alternatives --set php /usr/bin/php7.4

      - name: Install composer dependencies
        run: composer install

      - name: Run phpcs
        run: composer phpcs
