name: phpcs

on: [push]

jobs:
  phpcs:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup composer cache
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php7.4-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php7.4-composer-

      - name: Install composer dependencies
        run: composer install

      - name: Run phpcs
        run: composer phpcs
