name: phpunit tests

on: [push]

jobs:
  phpunit-tests:
    runs-on: ubuntu-16.04

    services:
      mysql:
        image: mysql:5.7.27
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup composer cache
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php7.4-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php7.4-composer-

      - name: Install composer dependencies
        run: composer install

      - name: Install WordPress
        run: ./bin/install-wp-tests.sh frontity_tests root root 127.0.0.1 latest

      - name: Run phpunit
        run: composer phpunit
