name: phpunit tests

on: [push]

jobs:
  phpunit-tests:
    runs-on: ubuntu-16.04

    services:
      mysql:
        image: mysql:5.7.27
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root

    strategy:
      matrix:
        php-version:
          - "5.6"
          - "7.3"

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup composer cache
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php${{ matrix.php-version }}-composer-

      - name: Install composer dependencies
        run: php${{ matrix.php-version }} /usr/bin/composer update  --no-ansi --no-interaction --no-progress

      - name: Install WordPress
        run: ./bin/install-wp-tests.sh frontity_tests root root 127.0.0.1 latest

      - name: Run phpunit
        run: php${{ matrix.php-version }} /usr/bin/scomposer phpunit
